version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - app/.env
    ports:
      - 5432:5432
  app:
    build: .
    env_file:
      - app/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on:
      - db

volumes:
  postgres_data: