version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=DATABASE_USER
      - POSTGRES_PASSWORD=DATABASE_PASSWORD
      - POSTGRES_DB=DATABASE
    ports:
      - 5432:5432
    container_name: book_api_db
  app:
    build: .
    env_file:
      - app/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on:
      - db
    container_name: book_api_app

volumes:
  postgres_data: