version: '3.8'

services:

  yourbooks_db:
    image: postgres:13
    container_name: yourbooks_db
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - PGUSER=$POSTGRES_USER
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - yourbooks_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    container_name: yourbooks
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@yourbooks_db/$POSTGRES_DB
      - DEBUG=$DEBUG
      - SECRET_KEY=$SECRET_KEY
      - ALGORITHM=$ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - 8000:80
    networks:
      - yourbooks_network
    depends_on:
      yourbooks_db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  yourbooks_network: