version: '3.8'

services:
  db:
    image: postgres:13
    container_name: book_api_db
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  app:
    build: .
    container_name: book_api_app
    environment:
      - DATABASE_URL=$DATABASE_URL
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on:
      - db

volumes:
  postgres_data: